import java.util.ArrayList;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        List<String> namesList = new ArrayList<>();

        for (String name : namesList){
            System.out.println(name);
        }

    }
}
