import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    Scanner sc = new Scanner(System.in);
    public void main(String[] args) {
        List<String> namesList = new ArrayList<>();
        namesList = collectNamesFromUser();
        for (String name : namesList){
            System.out.println("Hello "+name+"!");
        }
    }

    public List<String> collectNamesFromUser() {
        List<String> namesList = new ArrayList<>();
        String nameString = "";
        while (true){
            nameString = getNameFromUser();
            if (0<nameString.length()){
                namesList.add(nameString);
                /*for (String line : namesList) {
                    System.out.print("|"+line+"|");
                }*/
            } else {break;}
        }
        return namesList;
    }
    public String getNameFromUser() {
        System.out.println("Type a name (empty ends the input process)");
        sc = new Scanner(System.in);
        return sc.nextLine();
    }
}
