/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;

import java.io.ByteArrayInputStream;
import java.util.ArrayList;
import java.util.List;

import static org.testng.Assert.*;

public class AppTest {
    //------------------------collectNamesFromUser-------------------


    @Test public void Test_collectNamesFromUser_withList(){
        //given
        App classUnderTest = new App();
        List<String> testList = new ArrayList<>();
        String scannerFood = "";
        for (int i = 1; i<3; i++){
            testList.add("asdf"+i);
            scannerFood += "asdf" + i + System.lineSeparator();
        }
        System.setIn(new ByteArrayInputStream(scannerFood.getBytes()));
        //when
        List<String> testResultList = new ArrayList<>();
        testResultList = classUnderTest.collectNamesFromUser();
        //then
        assertEquals(testResultList, testList);
    } 
    
    
    
    //-----------------getNameFromUser-------------------
    @Test public void Test_getNameFromUser_returnsTheAddedString() {
        App classUnderTest = new App();
        System.setIn(new ByteArrayInputStream("Lajos".getBytes()));
        assertEquals(classUnderTest.getNameFromUser(), "Lajos");
    }
    //---------------------------------------------------
    @Test public void Test_getNameFromUser_returnsEmptyString(){
        //given
        App classUnderTest = new App();
        //when
        String nothing = ""+System.lineSeparator();
        System.setIn(new ByteArrayInputStream(nothing.getBytes()));
        //then
        assertTrue(1>classUnderTest.getNameFromUser().length());
    } 
}
